/*=============================================================================
	DeusEx_Registration_Reconstructed_Reconstructed.cpp
	DeusEx.dll reconstruction pass 13.

	Central class/package/native registration unit.

	Why centralized:
	- The earlier pass files each carried their own IMPLEMENT_CLASS for convenience.
	- A real VC98 build wants one canonical registration unit to avoid duplicate
	  static class objects and duplicate native exports.
	- Noexport native helpers XGameDirectory and UDumpLocation are registered here
	  because they are not fully covered by DeusExClasses.h autogenerated tails.
=============================================================================

	Pass18 packaging note:
	- This is the canonical full-content source snapshot for moving to the next
	  dialogue. Previous pass suffixes were removed from filenames only; runtime
	  code remains based on the latest strict passes.
=============================================================================*/

#include "DeusExReconstructedPrivate.h"

IMPLEMENT_PACKAGE(DeusEx);

DEUSEX_API FName DEUSEX_JoltView;

IMPLEMENT_CLASS(ADeusExPlayer);
IMPLEMENT_CLASS(AScriptedPawn);
IMPLEMENT_CLASS(ADeusExLevelInfo);
IMPLEMENT_CLASS(ADeusExDecoration);
IMPLEMENT_CLASS(ASkillManager);
IMPLEMENT_CLASS(ASkill);
IMPLEMENT_CLASS(AAugmentationManager);
IMPLEMENT_CLASS(AAugmentation);
IMPLEMENT_CLASS(UParticleIterator);
IMPLEMENT_CLASS(UDeusExSaveInfo);
IMPLEMENT_CLASS(UDeusExLog);
IMPLEMENT_CLASS(UDataVaultImageNote);
IMPLEMENT_CLASS(DDeusExGameEngine);
IMPLEMENT_CLASS(XGameDirectory);
IMPLEMENT_CLASS(UDumpLocation);
IMPLEMENT_CLASS(ULaserIterator);

IMPLEMENT_FUNCTION(ADeusExPlayer,1099,execGetDeusExVersion);
IMPLEMENT_FUNCTION(ADeusExPlayer,2100,execConBindEvents);
IMPLEMENT_FUNCTION(ADeusExDecoration,2101,execConBindEvents);
IMPLEMENT_FUNCTION(AScriptedPawn,2102,execConBindEvents);
IMPLEMENT_FUNCTION(AScriptedPawn,2105,execIsValidEnemy);
IMPLEMENT_FUNCTION(AScriptedPawn,2106,execGetAllianceType);
IMPLEMENT_FUNCTION(AScriptedPawn,2107,execGetPawnAllianceType);
IMPLEMENT_FUNCTION(AScriptedPawn,2108,execHaveSeenCarcass);
IMPLEMENT_FUNCTION(AScriptedPawn,2109,execAddCarcass);

IMPLEMENT_FUNCTION(ADeusExPlayer,3001,execSetBoolFlagFromString);
IMPLEMENT_FUNCTION(ADeusExPlayer,3002,execCreateHistoryObject);
IMPLEMENT_FUNCTION(ADeusExPlayer,3003,execCreateHistoryEvent);
IMPLEMENT_FUNCTION(ADeusExPlayer,3010,execCreateLogObject);
IMPLEMENT_FUNCTION(ADeusExPlayer,3011,execSaveGame);
IMPLEMENT_FUNCTION(ADeusExPlayer,3012,execDeleteSaveGameFiles);
IMPLEMENT_FUNCTION(ADeusExPlayer,3013,execCreateGameDirectoryObject);
IMPLEMENT_FUNCTION(ADeusExPlayer,3014,execCreateDataVaultImageNoteObject);
IMPLEMENT_FUNCTION(ADeusExPlayer,3015,execCreateDumpLocationObject);
IMPLEMENT_FUNCTION(ADeusExPlayer,3016,execUnloadTexture);
IMPLEMENT_FUNCTION(UParticleIterator,3017,execUpdateParticles);

// UDumpLocation behaviour is reconstructed in Source/UDumpLocation_Reconstructed.cpp.
IMPLEMENT_FUNCTION(UDumpLocation,3020,execGetFirstDumpFile);
IMPLEMENT_FUNCTION(UDumpLocation,3021,execGetNextDumpFile);
IMPLEMENT_FUNCTION(UDumpLocation,3022,execGetDumpFileIndex);
IMPLEMENT_FUNCTION(UDumpLocation,3023,execGetDumpFileCount);
IMPLEMENT_FUNCTION(UDumpLocation,3024,execOpenDumpFile);
IMPLEMENT_FUNCTION(UDumpLocation,3025,execCloseDumpFile);
IMPLEMENT_FUNCTION(UDumpLocation,3026,execDeleteDumpFile);
IMPLEMENT_FUNCTION(UDumpLocation,3027,execGetFirstDumpFileLocation);
IMPLEMENT_FUNCTION(UDumpLocation,3028,execGetNextDumpFileLocation);
IMPLEMENT_FUNCTION(UDumpLocation,3029,execGetDumpLocationIndex);
IMPLEMENT_FUNCTION(UDumpLocation,3030,execSelectDumpFileLocation);
IMPLEMENT_FUNCTION(UDumpLocation,3031,execGetDumpFileLocationInfo);
IMPLEMENT_FUNCTION(UDumpLocation,3032,execDeleteDumpFileLocation);
IMPLEMENT_FUNCTION(UDumpLocation,3033,execAddDumpFileLocation);
IMPLEMENT_FUNCTION(UDumpLocation,3034,execGetNextDumpFileLocationID);
IMPLEMENT_FUNCTION(UDumpLocation,3035,execGetCurrentUser);
IMPLEMENT_FUNCTION(UDumpLocation,3036,execSetPlayer);
IMPLEMENT_FUNCTION(UDumpLocation,3037,execSaveLocation);
IMPLEMENT_FUNCTION(UDumpLocation,3038,execLoadLocation);
IMPLEMENT_FUNCTION(UDumpLocation,3039,execHasLocationBeenSaved);
IMPLEMENT_FUNCTION(UDumpLocation,3040,execGetDumpFileLocationCount);

IMPLEMENT_FUNCTION(UDeusExSaveInfo,3075,execUpdateTimeStamp);

IMPLEMENT_FUNCTION(XGameDirectory,3080,execGetGameDirectory);
IMPLEMENT_FUNCTION(XGameDirectory,3081,execGetNewSaveFileIndex);
IMPLEMENT_FUNCTION(XGameDirectory,3082,execGenerateSaveFilename);
IMPLEMENT_FUNCTION(XGameDirectory,3083,execGenerateNewSaveFilename);
IMPLEMENT_FUNCTION(XGameDirectory,3084,execGetDirCount);
IMPLEMENT_FUNCTION(XGameDirectory,3085,execGetDirFilename);
IMPLEMENT_FUNCTION(XGameDirectory,3086,execSetDirType);
IMPLEMENT_FUNCTION(XGameDirectory,3087,execSetDirFilter);
IMPLEMENT_FUNCTION(XGameDirectory,3088,execGetSaveInfo);
IMPLEMENT_FUNCTION(XGameDirectory,3089,execGetSaveInfoFromDirectoryIndex);
IMPLEMENT_FUNCTION(XGameDirectory,3090,execGetTempSaveInfo);
IMPLEMENT_FUNCTION(XGameDirectory,3091,execDeleteSaveInfo);
IMPLEMENT_FUNCTION(XGameDirectory,3092,execPurgeAllSaveInfo);
IMPLEMENT_FUNCTION(XGameDirectory,3093,execGetSaveFreeSpace);
IMPLEMENT_FUNCTION(XGameDirectory,3094,execGetSaveDirectorySize);

void DeusExInitNames(void)
{
	guard(DeusExInitNames);

	static UBOOL bInitNames = TRUE;
	if (bInitNames == TRUE)
	{
		DEUSEX_JoltView = FName(TEXT("JoltView"), FNAME_Intrinsic);
		bInitNames = FALSE;
	}

	unguard;
}

/*-----------------------------------------------------------------------------
	The End.
-----------------------------------------------------------------------------*/
